development:
  adapter: postgresql
  database: film_budget_helper_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: film_budget_helper_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: film_budget_helper
  password: <%= ENV["PG_PROD"] %>
  username: film_budget_helper_production
